language: go
os:
  - linux
  - osx
install:
  - go get -t -d -v ./...
  - go version
  - go env
script:
  - go build ./selfupdate/
  - go build ./cmd/selfupdate-example/
  - go build ./cmd/detect-latest-release/
  - go build ./cmd/go-get-release/
  - |
    if [[ "${GITHUB_TOKEN}" != "" ]]; then
      go test -v -race -coverprofile=coverage.txt ./selfupdate
    else
      go test -v -race -short ./selfupdate
    fi
after_success:
  - if [ -f coverage.txt ]; then bash <(curl -s https://codecov.io/bash); fi
